#!/usr/bin/env bash
# Load — or mint, once — the HTTP Basic credentials for `opencode serve`.
#
# Meant to be *sourced*, not run: it exports OPENCODE_SERVER_USERNAME and
# OPENCODE_SERVER_PASSWORD into the calling shell. Requires $ROOT.
#
# `opencode serve` reads those two variables and demands Basic auth from every
# caller; relay reads the same file (app/config.py::OpenCodeConfig.credential)
# and presents the credential upstream. Generating it here rather than asking
# for one in .env is what makes `git clone && ./launch.sh` work with nothing to
# fill in — and skipping the password entirely is not an option, because an
# open `opencode serve` is a shell on this machine for anyone who reaches it.
#
# An OPENCODE_SERVER_PASSWORD already in the environment (from .env) always
# wins and is never overwritten.

AUTH_FILE="${OPENCODE_AUTH_FILE:-$ROOT/web/backend/data/opencode-auth.env}"

if [ -z "${OPENCODE_SERVER_PASSWORD:-}" ] && [ -f "$AUTH_FILE" ]; then
  # shellcheck disable=SC1090
  . "$AUTH_FILE"
fi

: "${OPENCODE_SERVER_USERNAME:=opencode}"

if [ -z "${OPENCODE_SERVER_PASSWORD:-}" ]; then
  # `head -c` bounds the read at the *source*. The obvious spelling —
  # `tr -dc … < /dev/urandom | head -c 32` — makes head close the pipe while
  # tr is still writing, and that SIGPIPE is a pipefail exit for the script
  # sourcing this file: launch.sh died before printing a single line.
  OPENCODE_SERVER_PASSWORD="$(
    LC_ALL=C head -c 24 /dev/urandom | base64 | LC_ALL=C tr -dc 'A-Za-z0-9')"
  mkdir -p "$(dirname "$AUTH_FILE")"
  (
    umask 077
    cat > "$AUTH_FILE" <<EOF
# Generated by scripts/opencode-auth.sh. Gitignored (web/backend/data/).
# Delete this file to rotate the credential; both processes read it.
OPENCODE_SERVER_USERNAME=$OPENCODE_SERVER_USERNAME
OPENCODE_SERVER_PASSWORD=$OPENCODE_SERVER_PASSWORD
EOF
  )
  echo "generated OpenCode credentials -> $AUTH_FILE" >&2
fi

export OPENCODE_SERVER_USERNAME OPENCODE_SERVER_PASSWORD
