"""Generate the README banner from the project logo.

Reads assets/logo.svg and writes assets/header.svg with the logo, the title,
the tagline and two chip rows. GitHub will not render one SVG referenced from
inside another, so the banner has to embed the logo's paths — generating it
means that copy is refreshed on every run instead of drifting.

The tagline duplicates the README's opening sentence. Change one, change both,
then re-run this.

    python3 tools/make_header.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOGO = ROOT / "assets/logo.svg"
LOGO_BOX = 256
OUT = ROOT / "assets/header.svg"
# The dashboard serves the same drawing as its sidebar mark and its favicon.
# Copied rather than re-drawn, so the logo file stays the only original.
PUBLIC = ROOT / "web/frontend/public/logo.svg"

TITLE = "Relay"
SUBTITLE = "LLM Dashboard"   # rendered muted, after a colon
TAGLINE = (
    "One OpenAI-compatible /v1 in front of local model servers and agent servers,",
    "and a record of what every request through it cost in latency and tokens.",
)
# Dot colours are GitHub's own, from github/linguist languages.yml, so the row
# reads as familiar rather than invented.
LANGUAGES = [
    ("Python", "#3572a5"),
    ("TypeScript", "#3178c6"),
    ("Shell", "#89e051"),
]
STACK = [(n, None) for n in ("FastAPI", "Astro", "React", "ECharts", "SQLite", "uv")]

PANEL_BG, PANEL_EDGE = "#0B0E14", "#1D2430"
CHIP_BG, CHIP_EDGE = "#11151D", "#2A3547"
TEXT, CHIP_TEXT, MUTED = "#E6EAF2", "#C3CAD8", "#8A94A6"
DISC = None  # the mark carries its own tile

SANS = "ui-sans-serif,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif"
MONO = "ui-monospace,SFMono-Regular,Menlo,Consolas,'DejaVu Sans Mono',monospace"

W = 1000
MARK, MARK_CY = 128.0, 116.0
TITLE_Y, TITLE_SIZE = 250, 62
TAGLINE_Y, TAGLINE_SIZE, LINE_H = 288, 18, 27
ROWS_Y, ROW_H = 356, 46
CHIP_H, CHIP_FS, CHIP_GAP, CHIP_PAD = 32, 14.0, 10.0, 15.0
DOT_R, DOT_GUTTER, ADVANCE = 4.0, 13.0, 0.6

rows = [r for r in (LANGUAGES, STACK) if r]
H = int(ROWS_Y + ROW_H * (len(rows) - 1) + CHIP_H + 24)


def logo_paths():
    raw = re.sub(r"<metadata>.*?</metadata>", "", LOGO.read_text(), flags=re.S)
    return raw[raw.index(">", raw.index("<svg")) + 1 : raw.rindex("</svg>")].strip()


def chip_row(items, y):
    widths = [
        CHIP_PAD * 2 + len(label) * CHIP_FS * ADVANCE + (DOT_GUTTER if dot else 0.0)
        for label, dot in items
    ]
    x = (W - (sum(widths) + CHIP_GAP * (len(items) - 1))) / 2
    parts = []
    for (label, dot), width in zip(items, widths):
        text_x = x + CHIP_PAD
        parts.append(
            f'<rect x="{x:.1f}" y="{y:g}" width="{width:.1f}" height="{CHIP_H}" '
            f'rx="{CHIP_H / 2:g}" fill="{CHIP_BG}" stroke="{CHIP_EDGE}" />'
        )
        if dot:
            parts.append(
                f'<circle cx="{text_x + DOT_R:.1f}" cy="{y + CHIP_H / 2:.1f}" '
                f'r="{DOT_R:g}" fill="{dot}" />'
            )
            text_x += DOT_GUTTER
        parts.append(
            f'<text x="{text_x:.1f}" y="{y + CHIP_H / 2 + 5:.1f}" font-family="{MONO}" '
            f'font-size="{CHIP_FS:g}" fill="{CHIP_TEXT}">{label}</text>'
        )
        x += width + CHIP_GAP
    return "\n  ".join(parts)


cx = W / 2
disc = (
    f'<circle cx="{cx:g}" cy="{MARK_CY:g}" r="{MARK * 28 / 24 / 2:.1f}" fill="{DISC}" />'
    if DISC
    else ""
)
taglines = "\n  ".join(
    f'<text x="{cx:g}" y="{TAGLINE_Y + i * LINE_H:g}" text-anchor="middle" '
    f'font-family="{SANS}" font-size="{TAGLINE_SIZE}" fill="{MUTED}">{line}</text>'
    for i, line in enumerate(TAGLINE)
)
chips = "\n  ".join(chip_row(row, ROWS_Y + i * ROW_H) for i, row in enumerate(rows))

OUT.write_text(f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" \
width="{W}" height="{H}" role="img" aria-label="{TITLE}: {SUBTITLE}">
  <!-- Generated by tools/make_header.py - edit that, not this. -->
  <rect x="0.5" y="0.5" width="{W - 1}" height="{H - 1}" rx="24" fill="{PANEL_BG}" \
stroke="{PANEL_EDGE}" />
  {disc}
  <g transform="translate({cx - MARK / 2:.1f},{MARK_CY - MARK / 2:.1f}) \
scale({MARK / LOGO_BOX:.6f})">
    {logo_paths()}
  </g>
  <text x="{cx:g}" y="{TITLE_Y}" text-anchor="middle" font-family="{SANS}" \
font-size="{TITLE_SIZE}" font-weight="700" letter-spacing="-1" fill="{TEXT}">{TITLE}<tspan fill="{MUTED}" font-weight="400">: {SUBTITLE}</tspan></text>
  {taglines}
  {chips}
</svg>
""")
PUBLIC.parent.mkdir(parents=True, exist_ok=True)
PUBLIC.write_text(LOGO.read_text())
print(f"wrote {OUT.relative_to(ROOT)} and {PUBLIC.relative_to(ROOT)}")
